name: Propose a new component 💠
description: I have a suggestion for a new component that is missing from your design system
labels: ["needs prioritization❗️"]
body:
  - type: markdown
    attributes:
      value: |
        Please do a search in our backlog to see if there are any issues or request already for this component.

  - type: textarea
    id: description
    attributes:
      label: Describe the component
      description: Describe the use-case for this component
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: If you have any examples or similar components feel free to include links or screenshots here


