name: Add new issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://https://github.com/orgs/digdir/projects/3/views/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
