name: Checks Packages
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'
      - '*.*js'
  push:
    paths:
      - 'packages/**'
jobs:
  checks:
    name: Builds, lints and tests code
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: yarn build
      - name: Types
        run: yarn types:react
      - name: Lint Code
        run: yarn lint:all
      - name: Lint CSS
        run: yarn lint-style
      - name: Test
        run: yarn test
