# Builds and deploys Storybook to github pages
# Requires github pages source settings to target the branch and folder in the deploy step from this action
name: Build and deploy Storybook
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Install modules
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Build source files 🔧
        run: pnpm build

      - name: Build docs 🔧
        run: pnpm build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: github-pages-deployment
          folder: docs/docs # Source folder (output from build step)
          target-folder: docs # Target folder (create a directory to put the deployment content in)