# https://github.com/anthonyhastings/turborepo-design-system
name: Release Snapshot

on:
  workflow_dispatch:

jobs:
  snapshot:
    name: Snapshot Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gh-setup
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Snapshot Release
        run: |
          yarn run version-packages --snapshot "${{ github.ref_name }}"
          echo '---'
          echo 'Detected Changes:'
          git diff
          echo '---'
          yarn run publish --tag "${{ github.ref_name }}" --no-git-tag
