name: Visual tests
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/visual-tests.yml
      - 'packages/**'
      - 'apps/storybook/**'
  push:
    branches:
      - main
      - next

jobs:
  checks:
    name: Build & run visual/interaction tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Necessary for Chromatic
          fetch-depth: 0
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: yarn build
      - name: Build storybook
        run: yarn build:storybook
      - name: Run Chromatic (visual and interaction tests)
        uses: chromaui/action@latest
        with:
          workingDir: apps/storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          autoAcceptChanges: '{main,next}'
